_wandb:
    value:
        cli_version: 0.22.0
        code_path: code/scripts/test_policy_optimization.py
        e:
            j0poql3o4lgwsjb3ufux6u8v2x7uco36:
                codePath: scripts/test_policy_optimization.py
                codePathLocal: scripts/test_policy_optimization.py
                cpu_count: 12
                cpu_count_logical: 24
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "982240026624"
                        used: "892924186624"
                email: naren@narendasan.com
                executable: /home/naren/tunable-cap/.venv/bin/python3
                gpu: NVIDIA GeForce RTX 5090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-5877db18-dd51-d7b5-ff7c-a18020c67bcd
                host: t-2000
                memory:
                    total: "67136741376"
                os: Linux-6.8.0-71-generic-x86_64-with-glibc2.39
                program: /home/naren/tunable-cap/scripts/test_policy_optimization.py
                python: CPython 3.11.12
                root: /home/naren/tunable-cap
                startedAt: "2025-09-18T21:25:04.861824Z"
                writerId: j0poql3o4lgwsjb3ufux6u8v2x7uco36
        m: []
        python_version: 3.11.12
        t:
            "1":
                - 2
                - 1
                - 3
                - 11
                - 12
                - 41
                - 49
                - 71
            "2":
                - 2
                - 1
                - 3
                - 11
                - 12
                - 41
                - 49
                - 71
            "3":
                - 13
                - 16
                - 35
            "4": 3.11.12
            "5": 0.22.0
            "6": 4.54.1
            "12": 0.22.0
            "13": linux-x86_64
batch_size:
    value: 32
buffer_size:
    value: 1000000
capture_video:
    value: true
cuda:
    value: false
end_e:
    value: 0.01
env_id:
    value: ALE/Breakout-v5
exp_name:
    value: _policy_optimizer
exploration_fraction:
    value: 0.1
gamma:
    value: 0.99
hf_entity:
    value: ""
learning_rate:
    value: 6.25e-05
learning_starts:
    value: 80000
n_atoms:
    value: 10
n_step:
    value: 3
num_envs:
    value: 1
prioritized_replay_alpha:
    value: 0.5
prioritized_replay_beta:
    value: 0.4
prioritized_replay_eps:
    value: 1e-06
save_model:
    value: true
seed:
    value: 1
start_e:
    value: 1
target_network_frequency:
    value: 8000
tau:
    value: 1
torch_deterministic:
    value: true
total_timesteps:
    value: 10000000
track:
    value: true
train_frequency:
    value: 4
upload_model:
    value: false
v_max:
    value: 10
v_min:
    value: -10
wandb_entity:
    value: narendasan
wandb_project_name:
    value: test_policy_optimizer
